// <auto-generated />
namespace Kimera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class trelloIdstring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trelloIdstring));
        
        string IMigrationMetadata.Id
        {
            get { return "201407012306130_trelloId string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
